#libraries in correct order
library('R6')
library('data.table')
library('plyr')
library('dplyr')
library('stringr')
library('png')
library('grid')
library('ggplot2')
library('jsonlite')

source(paste(getwd(),"R/Helpers/source-folder.R", sep = "/"))
source_folder(paste(getwd(),"R/Helpers/", sep = "/"))
source_folder(paste(getwd(),"R/Exporting/", sep = "/"))
source_folder(paste(getwd(),"R/Analysis/", sep = "/"))
source_folder(paste(getwd(),"R/Classes/", sep = "/"))
source_folder(paste(getwd(),"R/Preprocessing/", sep = "/"))
source_folder(paste(getwd(),"R/Graphing/", sep = "/"))
source_folder(paste(getwd(),"R/DataManipulation/", sep = "/"))
